apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete
  namespace: www
spec:
  concurrencyPolicy: Forbid
  schedule: "* */3 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: pod-delete
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'delete'
                - 'pods'
                - '--all'
                - '--namespace=www'
