apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachephp
spec:
  selector:
    matchLabels:
      app: apachephp
  replicas: 1
  template:
    metadata:
      labels:
        app: apachephp
    spec:
      volumes:
      - name: log
        emptyDir: {}
      - name: www-data
        emptyDir: {}
      containers:
      - name: apachephp
        image: olsarnow/apachephp
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: log
          mountPath: /var/log/apache2
        - mountPath: /var/www/html
          name: www-data
      initContainers:
      - name: git-cloner
        image: alpine/git
        args:
            - clone
            - --single-branch
            - --
            - https://github.com/olsarnow/sarnow.no
            - /data
        volumeMounts:
        - mountPath: /data
          name: www-data
